import type { Metadata } from "next";

import "./globals.css";
import { Toaster } from "sonner";

import { Ubuntu } from "next/font/google";

const ubuntu = Ubuntu({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-ubuntu",
  weight: ["300", "400", "500", "700"],
});

import TenStackProvider from "@/providers/TenStackProvider";
export const metadata: Metadata = {
  title: "Motion Finance App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={ubuntu.className}>
        <TenStackProvider>
          <main>{children}</main>
          <Toaster position="top-center" richColors />
        </TenStackProvider>
      </body>
    </html>
  );
}
